#端口号配置
server:
  port: 10086
  servlet-path: /stm
security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: SampleClientId
      clientSecret: secret
      accessTokenUri: http://192.168.0.100:8081/auth/oauth/token
      userAuthorizationUri: http://192.168.0.100:8081/auth/oauth/authorize
    resource:
      userInfoUri: http://192.168.0.100:8081/auth/user/me

# 数据库
spring:
  application:
    name: stm-server
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.77.218.225:3306/wangjunjie?useUnicode=true&characterEncoding=utf-8
    username: root
    password: weiwei18
#Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7071/eureka/
#Mapping位置配置
mybatis:
 mapperLocations: mapper/*.xml 
 




